export const JOIN_CONSTANTS = {
  MAX_DOMAIN_PATH_LENGTH: 10,
  MAX_TENANT_NM_LENGTH: 50,
  MAX_LOGIN_ID_LENGTH: 26,
  MAX_BSNS_REG_NO_LENGTH: 15,
  MAX_TENANT_TEL_LENGTH: 20,
  MAX_ADDR_LENGTH: 200,
  MAX_MGR_EMAIL_LENGTH: 100,
  MAX_MGR_NM_LENGTH: 50,
  MAX_MGR_TEL_LENGTH: 20
};
