import { Geist, Geist_Mono } from 'next/font/google';
import 'modern-css-reset/dist/reset.min.css';
import './globals.css';
import '@/shared/styles/main.scss';
import { GlobalErrorAlert } from '@/shared/component/popup/GlobalErrorAlert';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export const viewport = {
  width: 'device-width',
  initialScale: 1
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <GlobalErrorAlert />
        {children}
      </body>
    </html>
  );
}
