export const PARTNER_CONSTANTS = {
  DEFAULT_PAGE_SIZE: 10,
  MAX_PTNR_NM_LENGTH: 50,
  MAX_CEO_NM_LENGTH: 50,
  MAX_MAIN_SVC_LENGTH: 100,
  MAX_MAIN_MGR_LENGTH: 30,
  MAX_MGR_TEL_LENGTH: 20,
  MAX_NOTE_LENGTH: 500,

  PERIOD_TYPE_1MONTH: '1M',
  PERIOD_TYPE_3MONTHS: '3M',
  PERIOD_TYPE_6MONTHS: '6M',
  PERIOD_TYPE_1YEAR: '1Y'
};
